/**
 * Created by Utku on 02/03/2017.
 */
const types = {
    GET_ALL_QUERIES_SUCCESS: "GET_ALL_QUERIES_SUCCESS",
    GET_ALL_QUERIES_FAILED: "GET_ALL_QUERIES_FAILED",

    DELETE_QUERY_SUCCESS: "DELETE_QUERY_SUCCESS",
    DELETE_QUERY_FAILED: "DELETE_QUERY_FAILED",

    GET_QUERY_BY_NAME_FAILED: "GET_QUERY_BY_NAME_FAILED",
    GET_QUERY_BY_NAME_SUCCESS: "GET_QUERY_BY_NAME_SUCCESS",

    UPSERT_QUERY_SUCCESS: "UPSERT_QUERY_SUCCESS",
    UPSERT_QUERY_FAILED: "UPSERT_QUERY_FAILED",



    GET_ALL_FORMS_SUCCESS: "GET_ALL_FORMS_SUCCESS",
    GET_ALL_FORMS_FAILED: "GET_ALL_FORMS_FAILED",

    GET_FORM_BY_NAME_SUCCESS: "GET_FORM_BY_NAME_SUCCESS",
    GET_FORM_BY_NAME_FAILED: "GET_FORM_BY_NAME_FAILED",

    UPSERT_FORM_SUCCESS: "UPSERT_FORM_SUCCESS",
    UPSERT_FORM_FAILED: "UPSERT_FORM_FAILED",

    DELETE_FORM_SUCCESS: "DELETE_FORM_SUCCESS",
    DELETE_FORM_FAILED: "DELETE_FORM_FAILED",

    PUSH_NOTIFICATION : "PUSH_NOTIFICATION",
    CLEAR_NOTIFICATION : "CLEAR_NOTIFICATION"
}
export default types